name: plink2_indep_pairwise
description: Produce pruned set of variants in approximatelinkage equilibrium
keywords:
  - plink2
input:
  - meta:
      type: map
      description: sample information
  - bed:
      type: file
      description: PLINK 2 binary genotype table (bed)
      pattern: "*.{bed}"
  - bim:
      type: file
      description: PLINK extended MAP file
      pattern: "*.{bim}"
  - fam:
      type: file
      description: PLINK sample information file
      pattern: "*.{fam}"
  - win:
      type: value
      description: Window size in variant count or kilobase (if the 'kb' modifier is present) units, a variant count to shift the window at the end of each step, and a variance inflation factor (VIF) threshold.
      pattern: "*.{}"
  - step:
      type: value
      description: Variant count to shift the window at the end of each step.
      pattern: "*.{}"
  - r2:
      type: value
      description: R squared threshold
      pattern: "*.{}"
output:
  - meta:
      type: map
      description: sample information
  - prune_in:
      type: file
      description: Variants in linkage equilibrium
      pattern: "*.{prune.in}"
  - prune_out:
      type: file
      description: Excluded variants
      pattern: "*.{prune.out}"
authors:
  - @RuthEberhardt