name: bcftools_merge
description: Merge VCF files
keywords:
  - variant calling
  - merge
  - VCF
tools:
  - merge:
      description: |
        Index and merge VCF files, specifically merge 002.vcf and 003.vcf from a bcftools isec directory.
      homepage: http://samtools.github.io/bcftools/bcftools.html
      documentation: http://www.htslib.org/doc/bcftools.html
      doi: 10.1093/bioinformatics/btp352
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - disec_irectory:
      type: directory
      description: |
        Directory from bcftools isec containing 002.vcf.gz and 003.vcf.gz
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - vcf_gz:
      type: file
      description: VCF merged output file 
      pattern: "*.vcf.gz"
authors:
  - "@RuthEberhardt"

